"""Init database with TSVECTOR

Revision ID: ea413ff33804
Revises: 
Create Date: 2026-06-21 09:24:46.190582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea413ff33804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_simulation_runs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_simulation_runs', 'ai_weights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text('\'{"cost": 50, "time": 50}\'::jsonb'))
    op.alter_column('ai_simulation_runs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Running'::character varying"))
    op.alter_column('ai_simulation_runs', 'results_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ai_simulation_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_simulation_runs_id'), 'ai_simulation_runs', ['id'], unique=False)
    op.alter_column('app_projects', 'working_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('app_projects', 'working_days',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('app_projects', 'num_tasks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('app_projects', 'num_edges',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('app_projects', 'network_density',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('app_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Planning'::character varying"))
    op.alter_column('app_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_project_search', table_name='app_projects', postgresql_using='gin')
    op.create_index(op.f('ix_app_projects_id'), 'app_projects', ['id'], unique=False)
    op.alter_column('bridge_task_dependencies', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bridge_task_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'FS'::character varying"))
    op.alter_column('bridge_task_dependencies', 'lag_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_bridge_predecessor', table_name='bridge_task_dependencies')
    op.drop_index('idx_bridge_project', table_name='bridge_task_dependencies')
    op.drop_index('idx_bridge_successor', table_name='bridge_task_dependencies')
    op.create_index(op.f('ix_dim_topic_cost_id'), 'dim_topic_cost', ['id'], unique=False)
    op.create_index(op.f('ix_dim_topic_resources_id'), 'dim_topic_resources', ['id'], unique=False)
    op.create_index(op.f('ix_dim_topic_risk_id'), 'dim_topic_risk', ['id'], unique=False)
    op.create_index(op.f('ix_dim_topic_time_id'), 'dim_topic_time', ['id'], unique=False)
    op.alter_column('fact_tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_fact_tasks_project', table_name='fact_tasks')
    op.create_index(op.f('ix_fact_tasks_task_id'), 'fact_tasks', ['task_id'], unique=False)
    op.alter_column('project_baselines', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_baselines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('project_baselines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_project_baselines_id'), 'project_baselines', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_project_baselines_id'), table_name='project_baselines')
    op.alter_column('project_baselines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('project_baselines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('project_baselines', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_fact_tasks_task_id'), table_name='fact_tasks')
    op.create_index('idx_fact_tasks_project', 'fact_tasks', ['project_id'], unique=False)
    op.alter_column('fact_tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_dim_topic_time_id'), table_name='dim_topic_time')
    op.drop_index(op.f('ix_dim_topic_risk_id'), table_name='dim_topic_risk')
    op.drop_index(op.f('ix_dim_topic_resources_id'), table_name='dim_topic_resources')
    op.drop_index(op.f('ix_dim_topic_cost_id'), table_name='dim_topic_cost')
    op.create_index('idx_bridge_successor', 'bridge_task_dependencies', ['successor_id'], unique=False)
    op.create_index('idx_bridge_project', 'bridge_task_dependencies', ['project_id'], unique=False)
    op.create_index('idx_bridge_predecessor', 'bridge_task_dependencies', ['predecessor_id'], unique=False)
    op.alter_column('bridge_task_dependencies', 'lag_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bridge_task_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'FS'::character varying"))
    op.alter_column('bridge_task_dependencies', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_app_projects_id'), table_name='app_projects')
    op.create_index('idx_project_search', 'app_projects', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('app_projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Planning'::character varying"))
    op.alter_column('app_projects', 'network_density',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('app_projects', 'num_edges',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('app_projects', 'num_tasks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('app_projects', 'working_days',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('app_projects', 'working_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_simulation_runs_id'), table_name='ai_simulation_runs')
    op.alter_column('ai_simulation_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_simulation_runs', 'results_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ai_simulation_runs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Running'::character varying"))
    op.alter_column('ai_simulation_runs', 'ai_weights',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'{"cost": 50, "time": 50}\'::jsonb'))
    op.alter_column('ai_simulation_runs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
