import pandas as pd
import openpyxl
import re
import os
from datetime import datetime

class DSLIBExtractor:
    def __init__(self, file_path, output_dir, project_id):
        self.file_path = file_path
        self.output_dir = output_dir
        self.project_id = project_id
        self.wb = openpyxl.load_workbook(file_path, data_only=True)
        self.xl = pd.ExcelFile(file_path)
        
        self.hours_per_day = 8 # Default
        self.days_per_week = 5 # Default
        self.tasks = []
        self.resources = []
        self.risks = {}
        self.logic_edges = []
        self.task_resources = []
        
        self.agenda_working_hours = []
        self.agenda_working_days = []
        self.agenda_holidays = []
        
    def execute(self):
        print(f"Starting ETL for {self.file_path}")
        self.parse_agenda()
        self.parse_resources()
        self.parse_baseline_schedule()
        self.parse_risk_analysis()
        self.merge_and_transform()
        self.export_csv()
        print("Extraction and Transformation Complete.")
        
    def parse_agenda(self):
        try:
            df = self.xl.parse("Agenda")
            df.columns = df.columns.astype(str)
            yes_count = 0
            
            for i in range(len(df)):
                time_range = str(df.iloc[i, 0]).strip() if i < len(df) else ""
                is_working = str(df.iloc[i, 1]).strip() if i < len(df) else ""
                
                if "Generated by PMConverter" in time_range or "Generated by" in time_range:
                    continue
                    
                if time_range and time_range != 'nan':
                    self.agenda_working_hours.append({
                        "Time Range": time_range,
                        "Working": is_working
                    })
                    if is_working.lower() == 'yes':
                        yes_count += 1
                        
            if yes_count > 0:
                self.hours_per_day = yes_count
                
            if df.shape[1] > 4:
                for i in range(len(df)):
                    day_name = str(df.iloc[i, 3]).strip()
                    is_working = str(df.iloc[i, 4]).strip()
                    if day_name and day_name != 'nan':
                        self.agenda_working_days.append({
                            "Day": day_name,
                            "Working": is_working
                        })
                        
            if df.shape[1] > 6:
                for i in range(len(df)):
                    holiday = df.iloc[i, 6]
                    if not pd.isna(holiday) and str(holiday).strip() != 'nan':
                        if isinstance(holiday, datetime):
                            holiday_str = holiday.strftime("%Y-%m-%d")
                        else:
                            holiday_str = str(holiday).strip()
                        self.agenda_holidays.append({
                            "Holiday": holiday_str
                        })
                        
            print(f"[Agenda] Detected {self.hours_per_day} working hours per day.")
        except Exception as e:
            print(f"Error parsing Agenda: {e}")

    def get_cell_color(self, sheet_name, row, col):
        try:
            ws = self.wb[sheet_name]
            cell = ws.cell(row=row, column=col)
            if cell.fill and cell.fill.fill_type == "solid":
                return cell.fill.start_color.rgb
            return None
        except:
            return None

    def clean_cost(self, val):
        if pd.isna(val) or val == "":
            return 0.0
        val_str = str(val).replace(',', '').replace('$', '').replace('€', '').strip()
        try:
            return float(val_str)
        except:
            return 0.0


    def parse_time_components(self, val_str):
        res = {"sign": 1, "m": 0.0, "w": 0.0, "d": 0.0, "h": 0.0}
        if pd.isna(val_str) or not val_str:
            return res
            
        val_str = str(val_str).strip().lower()
        if val_str.startswith('-'):
            res["sign"] = -1
            val_str = val_str[1:]
        elif val_str.startswith('+'):
            res["sign"] = 1
            val_str = val_str[1:]
            
        matches = re.finditer(r'([\d\.]+)\s*([mwdh])', val_str)
        found_any = False
        
        for m in matches:
            found_any = True
            val = float(m.group(1))
            unit = m.group(2)
            if unit in res:
                res[unit] += val
                
        if not found_any and val_str.replace('.', '', 1).isdigit():
            res["d"] = float(val_str)
            
        return res

    def parse_time_to_hours(self, val_str):
        comps = self.parse_time_components(val_str)
        total = 0.0
        total += comps["h"]
        total += comps["d"] * self.hours_per_day
        total += comps["w"] * self.days_per_week * self.hours_per_day
        total += comps["m"] * 4 * self.days_per_week * self.hours_per_day
        return comps["sign"] * total

    def parse_resources(self):
        try:
            df = self.xl.parse("Resources")
            for idx, row in df.iterrows():
                if idx == 0 and str(row.iloc[0]).lower() == "id":
                    continue
                
                res_id = str(row.iloc[0]).strip()
                if not res_id or res_id == 'nan':
                    continue
                    
                res_name = str(row.iloc[1]).strip()
                if not res_name or pd.isna(res_name) or res_name == 'nan':
                    continue
                    
                res_type = str(row.iloc[2]).strip()
                avail_str = str(row.iloc[3]).strip()
                
                avail_match = re.search(r'([\d\.]+)', avail_str)
                capacity = float(avail_match.group(1)) if avail_match else 1.0
                
                cost_use = self.clean_cost(row.iloc[4])
                cost_unit = self.clean_cost(row.iloc[5])
                
                self.resources.append({
                    "ID": res_id,
                    "Name": res_name,
                    "Type": res_type,
                    "Availability": capacity,
                    "Cost/Use": cost_use,
                    "Cost/Unit": cost_unit
                })
            print(f"[Resources] Parsed {len(self.resources)} global resources.")
        except Exception as e:
            print(f"Error parsing Resources: {e}")

    def parse_baseline_schedule(self):
        df = self.xl.parse("Baseline Schedule")
        
        # Build ID to WBS mapping
        self.id_to_wbs = {}
        for idx, row in df.iterrows():
            t_id = str(row.iloc[0]).strip()
            wbs = str(row.iloc[2]).strip()
            if t_id and t_id != 'nan' and t_id.lower() != 'id':
                self.id_to_wbs[t_id] = wbs
                
        seen_edges = set()
        
        for idx, row in df.iterrows():
            excel_row = idx + 2
            color = self.get_cell_color("Baseline Schedule", excel_row, 1)
            
            if color == "FF9BBB59" or color == "009BBB59":
                task_id = str(row.iloc[0]).strip()
                if not task_id or task_id.lower() == 'id' or task_id == 'nan':
                    continue
                
                name = str(row.iloc[1]).strip()
                wbs = str(row.iloc[2]).strip()
                
                global_task_id = f"{self.project_id}_{wbs}"
                global_task_name = f"{wbs} - {name}"
                
                b_start = row.iloc[5]
                dur_str = str(row.iloc[7])
                dur_comps = self.parse_time_components(dur_str)
                
                elapsed_kws = [r'vận chuyển', r'vận tải', r'freight', r'shipping', r'transit', r'biển', r'sea', r'air', r'tàu', r'truck', r'transport', r'transportation', r'delivery', r'vessel', r'mobilisation', r'mobilization', r'demobilisation', r'demobilization', r'aging', r'curing', r'pumping', r'supply']
                agenda_override_kws = [r'loading', r'installation', r'assembly', r'preparation', r'grouting', r'fabrication', r'mounting', r'joint', r'connection', r'commissioning', r'research', r'supplier', r'system', r'training', r'design', r'development', r'dev', r'testing', r'test']
                
                def has_kw(kws, text):
                    pattern = r'\b(?:' + '|'.join(kws) + r')\b'
                    return bool(re.search(pattern, text, re.IGNORECASE))
                
                if has_kw(agenda_override_kws, name):
                    cal_type = "Agenda"
                elif has_kw(elapsed_kws, name):
                    cal_type = "Elapsed (24/7)"
                else:
                    cal_type = "Agenda"
                
                self.tasks.append({
                    "id": global_task_id,
                    "task_name": global_task_name,
                    "calendar_type": cal_type,
                    "baseline_start": b_start,
                    "duration_raw": dur_str,
                    "duration_months": dur_comps["m"],
                    "duration_weeks": dur_comps["w"],
                    "duration_days": dur_comps["d"],
                    "duration_hours": dur_comps["h"],
                    "material_cost": self.clean_cost(row.iloc[10]),
                    "internal_labor_cost": self.clean_cost(row.iloc[12])
                })
                
                # Parse Predecessors
                pred_str = str(row.iloc[3])
                if pred_str and not pd.isna(pred_str) and pred_str != "nan":
                    parts = pred_str.split(";")
                    for p in parts:
                        p = p.strip()
                        if p:
                            m = re.match(r'^(\d+)(FS|SS|FF|SF)?(.*)$', p)
                            if m:
                                p_id = m.group(1).strip()
                                p_wbs = self.id_to_wbs.get(p_id, p_id)
                                global_p_id = f"{self.project_id}_{p_wbs}"
                                p_type = m.group(2).strip() if m.group(2) else "FS"
                                p_lag_str = m.group(3).strip()
                                
                                edge_key = f"{global_task_id}_{global_p_id}_{p_type}_{p_lag_str}"
                                if edge_key not in seen_edges:
                                    seen_edges.add(edge_key)
                                    p_comps = self.parse_time_components(p_lag_str)
                                    self.logic_edges.append({
                                        "successor_task_id": global_task_id,
                                        "predecessor_task_id": global_p_id,
                                        "dependency_type": p_type,
                                        "lag_months": p_comps["m"],
                                        "lag_weeks": p_comps["w"],
                                        "lag_days": p_comps["d"],
                                        "lag_hours": p_comps["h"]
                                    })
                                    
                # Parse Successors -> Flip to Predecessors!
                succ_str = str(row.iloc[4])
                if succ_str and not pd.isna(succ_str) and succ_str != "nan":
                    parts = succ_str.split(";")
                    for p in parts:
                        p = p.strip()
                        if p:
                            m = re.match(r'^(FS|SS|FF|SF)?(\d+)(.*)$', p)
                            if m:
                                s_type = m.group(1).strip() if m.group(1) else "FS"
                                s_id = m.group(2).strip()
                                s_lag_str = m.group(3).strip()
                                
                                s_wbs = self.id_to_wbs.get(s_id, s_id)
                                global_s_id = f"{self.project_id}_{s_wbs}"
                                
                                edge_key = f"{global_s_id}_{global_task_id}_{s_type}_{s_lag_str}"
                                if edge_key not in seen_edges:
                                    seen_edges.add(edge_key)
                                    s_comps = self.parse_time_components(s_lag_str)
                                    self.logic_edges.append({
                                        "successor_task_id": global_s_id,
                                        "predecessor_task_id": global_task_id,
                                        "dependency_type": s_type,
                                        "lag_months": s_comps["m"],
                                        "lag_weeks": s_comps["w"],
                                        "lag_days": s_comps["d"],
                                        "lag_hours": s_comps["h"]
                                    })
                
                # Parse Resource Demand
                res_str = str(row.iloc[8])
                if res_str and not pd.isna(res_str) and res_str != "nan":
                    parts = res_str.split(";")
                    for p in parts:
                        p = p.strip()
                        if p:
                            m = re.match(r'^([^\[]+)(?:\[([\d\.]+)\s+#([\d\.]+)\])?$', p)
                            if m:
                                r_name = m.group(1).strip()
                                r_qty = float(m.group(2)) if m.group(2) else 1.0
                                
                                self.task_resources.append({
                                    "task_id": global_task_id,
                                    "resource_id": r_name,
                                    "request_quantity": r_qty
                                })
                                
        # Post-process: Add orphan tasks (tasks with no predecessors and no incoming flipped successors)
        edge_task_ids = set(edge["successor_task_id"] for edge in self.logic_edges)
        for t in self.tasks:
            global_t_id = t["id"]
            if global_t_id not in edge_task_ids:
                self.logic_edges.append({
                    "successor_task_id": global_t_id,
                    "predecessor_task_id": "",
                    "dependency_type": "",
                    "lag_months": 0.0,
                    "lag_weeks": 0.0,
                    "lag_days": 0.0,
                    "lag_hours": 0.0
                })
                                
        print(f"[Baseline] Parsed {len(self.tasks)} leaf tasks, {len(self.logic_edges)} total logic edges, {len(self.task_resources)} resource demands.")

    def parse_risk_analysis(self):
        try:
            df = self.xl.parse("Risk Analysis")
            for idx, row in df.iterrows():
                excel_row = idx + 2
                color = self.get_cell_color("Risk Analysis", excel_row, 1)
                
                if color == "FF9BBB59" or color == "009BBB59":
                    task_id = str(row.iloc[0]).strip()
                    if not task_id or task_id.lower() == 'id' or task_id == 'nan':
                        continue
                    
                    t_wbs = self.id_to_wbs.get(task_id, task_id)
                    global_task_id = f"{self.project_id}_{t_wbs}"
                    
                    desc = str(row.iloc[3]).lower()
                    self.risks[global_task_id] = {
                        "desc": desc,
                        "o_raw": row.iloc[4],
                        "m_raw": row.iloc[5],
                        "p_raw": row.iloc[6]
                    }
        except Exception as e:
            print(f"Error parsing Risk Analysis: {e}")

    def merge_and_transform(self):
        for task in self.tasks:
            t_id = task['id']
            b_dur = self.parse_time_to_hours(task.pop('duration_raw'))
            
            if t_id in self.risks:
                r = self.risks[t_id]
                desc = r['desc']
                o_raw, m_raw, p_raw = r['o_raw'], r['m_raw'], r['p_raw']
                
                if pd.isna(o_raw) or o_raw == "":
                    o_abs, m_abs, p_abs = b_dur, b_dur, b_dur
                else:
                    o_val = float(o_raw)
                    m_val = float(m_raw)
                    p_val = float(p_raw)
                    
                    if "standard" in desc:
                        o_abs = b_dur * (o_val / 100.0)
                        m_abs = b_dur * (m_val / 100.0)
                        p_abs = b_dur * (p_val / 100.0)
                    elif "manual" in desc:
                        o_abs, m_abs, p_abs = o_val, m_val, p_val
                    else:
                        o_abs, m_abs, p_abs = b_dur, b_dur, b_dur
                        
                pert_estimate = (o_abs + 4 * m_abs + p_abs) / 6.0
                reserve = p_abs - o_abs
                
                task['optimistic_duration'] = round(o_abs, 2)
                task['most_probable_duration'] = round(m_abs, 2)
                task['pessimistic_duration'] = round(p_abs, 2)
                task['pert_3_point_estimate'] = round(pert_estimate, 2)
                task['contingency_reserve'] = round(reserve, 2)
            else:
                task['optimistic_duration'] = b_dur
                task['most_probable_duration'] = b_dur
                task['pessimistic_duration'] = b_dur
                task['pert_3_point_estimate'] = b_dur
                task['contingency_reserve'] = 0.0
                
            # Initialize all other PMBOK 72 features to 0.0 to maintain consistent schema
            task['baseline_start_relative'] = 0.0
            
            # G1
            task['subcontracting_cost'] = 0.0
            task['overtime_crashing_cost'] = 0.0
            task['equipment_cost'] = 0.0
            task['direct_transportation'] = 0.0
            task['energy_fuel_cost'] = 0.0
            task['testing_and_inspection'] = 0.0
            
            # G2
            task['pm_overhead'] = 0.0
            task['facility_rent'] = 0.0
            task['utilities'] = 0.0
            task['communication_cost'] = 0.0
            task['internal_training'] = 0.0
            task['quality_mgmt_overhead'] = 0.0
            
            # G4
            task['permits_and_licensing'] = 0.0
            task['project_insurance'] = 0.0
            task['warranty_and_after_sales'] = 0.0
            task['regulatory_compliance'] = 0.0
            
            # G5
            task['inventory_holding_cost'] = 0.0
            task['ordering_cost'] = 0.0
            task['shortage_stockout'] = 0.0
            task['obsolescence_cost'] = 0.0
            task['international_freight'] = 0.0
            task['packaging_and_handling'] = 0.0
            task['reverse_logistics'] = 0.0
            
            # G6
            task['wait_queue_time'] = 0.0
            task['setup_transition_time'] = 0.0
            task['induction_time'] = 0.0
            task['lead_time'] = 0.0
            
            # G7
            task['allocated_quantity'] = 0.0
            task['labor_productivity'] = 0.0
            task['equipment_utilization'] = 0.0
            task['resource_substitutability'] = 0.0
            
            # G9
            task['technical_complexity'] = 0.0
            task['rework_probability'] = 0.0
            task['external_dependency_level'] = 0.0
            task['management_reserve'] = 0.0
            task['weather_seasonal_risk'] = 0.0
            task['technology_risk'] = 0.0
            
            # G11
            task['required_skill_level'] = 0.0
            task['staff_experience'] = 0.0
            task['learning_curve_effect'] = 0.0
            task['hr_stability_risk'] = 0.0
            task['cross_functional_coordination'] = 0.0
            task['occupational_safety_risk'] = 0.0
            
            # G12
            task['environmental_impact'] = 0.0
            task['waste_disposal_cost'] = 0.0
            task['community_social_impact'] = 0.0
            task['carbon_tax_credit'] = 0.0
            task['esg_compliance'] = 0.0

    def export_csv(self):
        os.makedirs(self.output_dir, exist_ok=True)
        
        pd.DataFrame(self.tasks).to_csv(os.path.join(self.output_dir, "tasks.csv"), index=False)
        pd.DataFrame(self.resources).to_csv(os.path.join(self.output_dir, "resources.csv"), index=False)
        pd.DataFrame(self.logic_edges).to_csv(os.path.join(self.output_dir, "predecessors.csv"), index=False)
        pd.DataFrame(self.task_resources).to_csv(os.path.join(self.output_dir, "task_resources.csv"), index=False)
        
        pd.DataFrame(self.agenda_working_hours).to_csv(os.path.join(self.output_dir, "agenda_working_hours.csv"), index=False)
        pd.DataFrame(self.agenda_working_days).to_csv(os.path.join(self.output_dir, "agenda_working_days.csv"), index=False)
        pd.DataFrame(self.agenda_holidays).to_csv(os.path.join(self.output_dir, "agenda_holidays.csv"), index=False)
        
        print(f"Exported 7 CSV files to {self.output_dir}")

if __name__ == "__main__":
    input_dir = r"E:\University\Year 3-3\DA3\ai_pipeline\data\raw\DSLIB_Logistics_Subset\use"
    base_out_dir = r"E:\University\Year 3-3\DA3\ai_pipeline\data\processed"
    
    for filename in os.listdir(input_dir):
        if filename.endswith(".xlsx") and not filename.startswith("~$"):
            file_path = os.path.join(input_dir, filename)
            proj_code = filename.split(" ")[0]
            out_dir = os.path.join(base_out_dir, proj_code)
            
            try:
                extractor = DSLIBExtractor(file_path, out_dir, proj_code)
                extractor.execute()
            except Exception as e:
                print(f"Failed to process {filename}: {e}")
