import pandas as pd
import openpyxl
import re
import os
from datetime import datetime

class DSLIBExtractor:
    def __init__(self, file_path, output_dir):
        self.file_path = file_path
        self.output_dir = output_dir
        self.wb = openpyxl.load_workbook(file_path, data_only=True)
        self.xl = pd.ExcelFile(file_path)
        
        self.hours_per_day = 8 # Default
        self.project_info = {}
        self.tasks = []
        self.resources = []
        self.risks = {}
        self.logic_edges = []
        self.task_resources = []
        self.agenda_working_hours = []
        self.agenda_working_days = []
        self.agenda_holidays = []
        
    def execute(self):
        print(f"Starting ETL for {self.file_path}")
        self.parse_agenda()
        self.parse_resources()
        self.parse_baseline_schedule()
        self.parse_risk_analysis()
        self.merge_and_transform()
        self.export_csv()
        print("Extraction and Transformation Complete.")
        
    def parse_agenda(self):
        try:
            df = self.xl.parse("Agenda")
            df.columns = df.columns.astype(str)
            yes_count = 0
            
            # Parse Working Hours (Col 0 and Col 1)
            for i in range(len(df)):
                time_range = str(df.iloc[i, 0]).strip()
                is_working = str(df.iloc[i, 1]).strip()
                if "Generated by PMConverter" in time_range or "Generated by" in time_range:
                    continue
                if time_range and time_range != 'nan':
                    self.agenda_working_hours.append({
                        "Time Range": time_range,
                        "Working": is_working
                    })
                    if is_working.lower() == 'yes':
                        yes_count += 1
                        
            if yes_count > 0:
                self.hours_per_day = yes_count
                
            # Parse Working Days (Col 3 and Col 4)
            if df.shape[1] > 4:
                for i in range(len(df)):
                    day_name = str(df.iloc[i, 3]).strip()
                    is_working = str(df.iloc[i, 4]).strip()
                    if day_name and day_name != 'nan':
                        self.agenda_working_days.append({
                            "Day": day_name,
                            "Working": is_working
                        })
                        
            # Parse Holidays (Col 6)
            if df.shape[1] > 6:
                for i in range(len(df)):
                    holiday = df.iloc[i, 6]
                    if not pd.isna(holiday) and str(holiday).strip() != 'nan':
                        # Convert to string if it's a timestamp
                        if isinstance(holiday, datetime):
                            holiday_str = holiday.strftime("%Y-%m-%d")
                        else:
                            holiday_str = str(holiday).strip()
                        self.agenda_holidays.append({
                            "Holiday": holiday_str
                        })
                        
            print(f"[Agenda] Detected {self.hours_per_day} working hours per day.")
            print(f"[Agenda] Parsed {len(self.agenda_working_hours)} hours rows, {len(self.agenda_working_days)} days rows, {len(self.agenda_holidays)} holidays.")
        except Exception as e:
            print(f"Error parsing Agenda: {e}")

    def get_cell_color(self, sheet_name, row, col):
        try:
            ws = self.wb[sheet_name]
            cell = ws.cell(row=row, column=col)
            if cell.fill and cell.fill.fill_type == "solid":
                return cell.fill.start_color.rgb
            return None
        except:
            return None

    def clean_cost(self, val):
        if pd.isna(val) or val == "":
            return 0.0
        val_str = str(val).replace(',', '').replace('$', '').replace('€', '').strip()
        try:
            return float(val_str)
        except:
            return 0.0

    def parse_duration(self, val_str):
        if pd.isna(val_str) or not val_str:
            return 0.0
        val_str = str(val_str).lower().strip()
        total_hours = 0.0
        
        d_match = re.search(r'([\d\.]+)\s*d', val_str)
        if d_match:
            total_hours += float(d_match.group(1)) * self.hours_per_day
            
        h_match = re.search(r'([\d\.]+)\s*h', val_str)
        if h_match:
            total_hours += float(h_match.group(1))
            
        return total_hours

    def parse_resources(self):
        try:
            df = self.xl.parse("Resources")
            for idx, row in df.iterrows():
                if idx == 0 and str(row.iloc[0]).lower() == "id":
                    continue
                
                res_id = str(row.iloc[0]).strip() # Keep exact ID
                if not res_id or res_id == 'nan':
                    continue
                    
                res_name = str(row.iloc[1]).strip()
                if not res_name or pd.isna(res_name) or res_name == 'nan':
                    continue
                    
                res_type = str(row.iloc[2]).strip()
                avail_str = str(row.iloc[3]).strip()
                
                avail_match = re.search(r'([\d\.]+)', avail_str)
                capacity = float(avail_match.group(1)) if avail_match else 1.0
                
                cost_use = self.clean_cost(row.iloc[4])
                cost_unit = self.clean_cost(row.iloc[5])
                
                self.resources.append({
                    "ID": res_id,
                    "Name": res_name,
                    "Type": res_type,
                    "Availability": capacity,
                    "Cost/Use": cost_use,
                    "Cost/Unit": cost_unit
                })
            print(f"[Resources] Parsed {len(self.resources)} global resources.")
        except Exception as e:
            print(f"Error parsing Resources: {e}")

    def parse_baseline_schedule(self):
        df = self.xl.parse("Baseline Schedule")
        
        for idx, row in df.iterrows():
            excel_row = idx + 2
            color = self.get_cell_color("Baseline Schedule", excel_row, 1)
            
            if color == "FF316AC5" or color == "00316AC5": 
                continue
                
            wbs = str(row.iloc[2]).strip()
            task_id_raw = str(row.iloc[0]).strip()
            if not task_id_raw or task_id_raw.lower() == 'id' or task_id_raw == 'nan':
                continue
            
            task_id = task_id_raw # Keep exact ID string
            name = str(row.iloc[1]).strip()
            
            if wbs == "1":
                self.project_info['name'] = name
                self.project_info['target_deadline'] = row.iloc[6]
            
            if color == "FF9BBB59" or color == "009BBB59":
                dur_str = str(row.iloc[7])
                planned_duration = self.parse_duration(dur_str)
                
                self.tasks.append({
                    "ID": task_id,
                    "Name": name,
                    "WBS": wbs,
                    "Baseline Start": row.iloc[5],
                    "Duration": planned_duration,
                    "Fixed Cost": self.clean_cost(row.iloc[10]),
                    "Variable Cost": self.clean_cost(row.iloc[12])
                })
                
                pred_str = str(row.iloc[3])
                if pred_str and not pd.isna(pred_str) and pred_str != "nan":
                    parts = pred_str.split(";")
                    for p in parts:
                        p = p.strip()
                        if p:
                            m = re.match(r'^(\S+?)([a-zA-Z]{2})?(.*)$', p)
                            if m:
                                p_id = m.group(1)
                                p_type = m.group(2) if m.group(2) else "FS"
                                p_lag = self.parse_duration(m.group(3))
                                self.logic_edges.append({
                                    "Predecessors": p_id,
                                    "Successors": task_id,
                                    "Type": p_type,
                                    "Lag": p_lag
                                })
                
                res_str = str(row.iloc[8])
                if res_str and not pd.isna(res_str) and res_str != "nan":
                    parts = res_str.split(";")
                    for p in parts:
                        p = p.strip()
                        if p:
                            m = re.match(r'^([^\[]+)(?:\[([\d\.]+)\s+#([\d\.]+)\])?$', p)
                            if m:
                                r_name = m.group(1).strip()
                                r_qty = float(m.group(2)) if m.group(2) else 1.0
                                
                                self.task_resources.append({
                                    "Task ID": task_id,
                                    "Resource Name": r_name,
                                    "Requested Quantity": r_qty
                                })
                                
        print(f"[Baseline] Parsed {len(self.tasks)} leaf tasks, {len(self.logic_edges)} logic edges, {len(self.task_resources)} resource demands.")

    def parse_risk_analysis(self):
        try:
            df = self.xl.parse("Risk Analysis")
            for idx, row in df.iterrows():
                excel_row = idx + 2
                color = self.get_cell_color("Risk Analysis", excel_row, 1)
                
                if color == "FF9BBB59" or color == "009BBB59":
                    task_id_raw = str(row.iloc[0]).strip()
                    if not task_id_raw or task_id_raw.lower() == 'id' or task_id_raw == 'nan':
                        continue
                    task_id = task_id_raw
                    
                    desc = str(row.iloc[3]).lower()
                    self.risks[task_id] = {
                        "desc": desc,
                        "o_raw": row.iloc[4],
                        "m_raw": row.iloc[5],
                        "p_raw": row.iloc[6]
                    }
        except Exception as e:
            print(f"Error parsing Risk Analysis: {e}")

    def merge_and_transform(self):
        for task in self.tasks:
            t_id = task['ID']
            b_dur = task['Duration']
            
            if t_id in self.risks:
                r = self.risks[t_id]
                desc = r['desc']
                o_raw, m_raw, p_raw = r['o_raw'], r['m_raw'], r['p_raw']
                
                if pd.isna(o_raw) or o_raw == "":
                    o_abs, m_abs, p_abs = b_dur, b_dur, b_dur
                else:
                    o_val = float(o_raw)
                    m_val = float(m_raw)
                    p_val = float(p_raw)
                    
                    if "standard" in desc:
                        o_abs = b_dur * (o_val / 100.0)
                        m_abs = b_dur * (m_val / 100.0)
                        p_abs = b_dur * (p_val / 100.0)
                    elif "manual" in desc:
                        o_abs, m_abs, p_abs = o_val, m_val, p_val
                    else:
                        o_abs, m_abs, p_abs = b_dur, b_dur, b_dur
                        
                pert_estimate = (o_abs + 4 * m_abs + p_abs) / 6.0
                reserve = p_abs - o_abs
                
                task['Optimistic'] = round(o_abs, 2)
                task['Most Probable'] = round(m_abs, 2)
                task['Pessimistic'] = round(p_abs, 2)
                task['PERT Expected'] = round(pert_estimate, 2)
                task['Reserve'] = round(reserve, 2)
            else:
                task['Optimistic'] = b_dur
                task['Most Probable'] = b_dur
                task['Pessimistic'] = b_dur
                task['PERT Expected'] = b_dur
                task['Reserve'] = 0.0

    def export_csv(self):
        os.makedirs(self.output_dir, exist_ok=True)
        
        pd.DataFrame(self.tasks).to_csv(os.path.join(self.output_dir, "tasks.csv"), index=False)
        pd.DataFrame(self.resources).to_csv(os.path.join(self.output_dir, "resources.csv"), index=False)
        pd.DataFrame(self.logic_edges).to_csv(os.path.join(self.output_dir, "logic_edges.csv"), index=False)
        pd.DataFrame(self.task_resources).to_csv(os.path.join(self.output_dir, "task_resources.csv"), index=False)
        
        pd.DataFrame(self.agenda_working_hours).to_csv(os.path.join(self.output_dir, "agenda_working_hours.csv"), index=False)
        pd.DataFrame(self.agenda_working_days).to_csv(os.path.join(self.output_dir, "agenda_working_days.csv"), index=False)
        pd.DataFrame(self.agenda_holidays).to_csv(os.path.join(self.output_dir, "agenda_holidays.csv"), index=False)
        
        print(f"Exported 7 CSV files to {self.output_dir}")

if __name__ == "__main__":
    file = r"E:\University\Year 3-3\DA3\ai_pipeline\data\raw\DSLIB_Logistics_Subset\use\C2011-07 Patient Transport System.xlsx"
    out_dir = r"E:\University\Year 3-3\DA3\ai_pipeline\data\processed\C2011-07"
    extractor = DSLIBExtractor(file, out_dir)
    extractor.execute()
